# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  #https://app.vagrantup.com/ubuntu/boxes/trusty64
  config.vm.box = "ubuntu/trusty64"
  
  config.vm.define "blog" do |blog|
  end
  
  config.vm.provider "blog" do |blog|
    blog.memory = 2048
	blog.cpus = 2
  end

  config.vm.provision :shell, path: "install-rvm.sh", args: "stable", privileged: false
  config.vm.provision :shell, path: "install-ruby.sh", args: "2.5.0", privileged: false
  config.vm.provision :shell, path: "install-ruby.sh", args: "5.1.4 rails haml", privileged: false
  config.vm.provision :shell, path: "vagrant_load.sh", privileged: false

  # Don't load the vagrant file and shell
  config.vm.synced_folder ".", "/vagrant", disabled:true
  
  config.vm.network :forwarded_port, guest: 3000, host: 3000
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
end
